export const categories = [
  // Original categories
  "calibration",
  "scales and weights",
  "lab equipment",
  "process control and tank weighing",
  "force measurements",
  "material testing",
  "torque measurement",
  "dimension speed and pressure",
  
  // A categories
  "Accelerometers",
  "Air Preparation Units",
  "Air Velocity Meters",
  "Alarm Annunciators",
  "Alignment Tools",
  "Anemometers",
  "Appliance Testers",
  
  // B categories
  "Band Heaters",
  "Barriers",
  "Battery Testers",
  "Bimetal Thermometers",
  "Blackbody Sources",
  "Bolt Tension Monitors",
  "Borescopes",
  "BTU Meters",
  
  // C categories
  "Cable Heaters",
  "Calibration Pumps",
  "Carbon Dioxide (CO2) Detectors",
  "Cartridge Heaters",
  "Ceramic Fiber Heaters",
  "Circuit Testers",
  "Circular Chart Recorders",
  "Circulation Heaters",
  "Clamp Meters",
  "Colorimeters",
  "Combustion Analyzers",
  "Conductivity Sensors",
  "Conductivity Transmitters",
  "Continuity Testers",
  "Control Panel Enclosures",
  "Coriolis Mass Flow Meters",
  "Corrosion Monitoring",
  
  // D categories
  "Damper Drives",
  "Data Loggers",
  "Deadweight Testers",
  "Decade Boxes",
  "Density Meters",
  "Dew Point Meters",
  "Dewpoint Calibrators",
  "Differential Pressure Flow Meters",
  "Digital Scales",
  "Digital Thermometers",
  "Dissolved Oxygen Meters",
  "Dosing Modules",
  "Dry Block Calibrators",
  
  // E categories
  "Eddy Current Testers",
  "Electrical Calibrators",
  "Electrical Multifunction Calibrators",
  "Electrical Testers",
  "Electrical Testing Kits",
  "Electromagnetic Flow Meters",
  "Emission Analyzers",
  "Environmental Monitoring Systems",
  
  // F categories
  "Fixed Infrared Thermometers",
  "Flame Detectors",
  "Flaw Detectors",
  "Flexible Heaters",
  "Flow Indicators",
  "Flow Meter Monitors",
  "Flow Meters",
  "Flow Regulators",
  "Flow Switches",
  "Flow Transmitters",
  "Fluidized Temperature Baths",
  "Fluorometers",
  "Force Gauges",
  
  // G categories
  "Gas Analyzers",
  "Gas Detectors",
  "Ground Resistance Meters",
  
  // H categories
  "Handheld Infrared Thermometers",
  "Hardness Testers",
  "HART Communicators",
  "Hazardous Area Telephones",
  "Heat Tracing",
  "Heated Platen",
  "Heaters",
  "Horns and Strobes",
  "Human-Machine Interfaces",
  "Humidity Calibrators",
  "Humidity Meters",
  
  // I categories
  "Inclinometers",
  "Indoor Air Quality (IAQ) Meters",
  "Industrial PCs",
  "Industrial Scales",
  "Inertial Sensors",
  "Infrared Sources",
  "Infrared Thermometers",
  "Insulation Testers",
  "Inverters",
  "ISE Meters",
  "Isolators",
  "ITS-90 Fixed Point Cells",
  
  // L categories
  "Leak Detectors",
  "Level Indicators",
  "Level Instruments",
  "Level Switches",
  "Level Transmitters",
  "Light Meters",
  "Linear Position Sensors",
  "Liquid Bath Calibrators",
  "Lithium Ion Storage",
  "Load Cells",
  "Loop Calibrators",
  "Low Resistance Ohmmeters",
  "LP Regulators",
  
  // M categories
  "Magmeters",
  "Magnetic Thickness Gauges",
  "Mass Test Instruments",
  "Metering Pumps",
  "Milliohm Meters",
  "Moisture Analyzers",
  "Moisture Calibrators",
  "Moisture Meters",
  "Multifunction Process Calibrators",
  "Multimeters",
  
  // N categories
  "Network Cable Testers",
  "Non-Destructive Testing (NDT) Equipment",
  
  // O categories
  "ORP Meters",
  "Oscilloscopes",
  "Oxygen Analyzers",
  "Oxygen Transmitters",
  
  // P categories
  "Paddlewheel Flow Meters",
  "Panel Meters",
  "Particle Counters",
  "pH and ORP Sensors",
  "pH Meters",
  "pH Transmitters",
  "Phase Rotation Testers",
  "Phasing Testers",
  "Photometers",
  "Photometric Measurement",
  "Pitot Static Testers",
  "Platinum Resistance Thermometers",
  "PLCs",
  "Pneumatic Cylinders",
  "Positive Displacement Flow Meters",
  "Power Controllers",
  "Power Positioners",
  "Power Quality Analyzers",
  "Power Supplies",
  "Precision Thermometers",
  "Pressure Calibration Kits",
  "Pressure Calibrators",
  "Pressure Controllers",
  "Pressure Gauges",
  "Pressure Indicators",
  "Pressure Multifunction Calibrators",
  "Pressure Sensors",
  "Pressure Switches",
  "Pressure Transducers",
  "Pressure Transmitters",
  "Process Controllers",
  "Process Heaters",
  "Proximity Sensors",
  
  // R categories
  "Recorders",
  "Refractometers",
  "Refrigeration Test Equipment",
  "Remote Visual Inspection",
  "Resistance Standards",
  "Rotameters",
  "Roughness Testers",
  "RTD Calibrators",
  "RTD Sensors",
  
  // S categories
  "Sampling Systems",
  "Signal Conditioners",
  "Sound Level Meters",
  "Steam and Condensate Management",
  "Stopwatches",
  "Strip Chart Recorders",
  "Strip Heaters",
  "Stroboscopes",
  "Surge Protectors",
  
  // T categories
  "Tachometers",
  "Temperature Calibrators",
  "Temperature Controllers",
  "Temperature Multifunction Calibrators",
  "Temperature Switches",
  "Temperature Transmitters",
  "Test Weight Sets",
  "Thermal Imagers",
  "Thermal Mass Flow Meters",
  "Thermocouple Calibrators",
  "Thermocouple Reference Equipment",
  "Thermocouple Thermometers",
  "Thermocouples",
  "Thermometers",
  "Tiltmeters",
  "Timers",
  "Torque Gauges",
  "Tubular Heaters",
  "Turbidity Meters",
  "Turbine Flow Meters",
  
  // U categories
  "Ultrasonic Flow Meters",
  "Ultrasonic Thickness Gauges",
  
  // V categories
  "Valve Motor Drive Controllers",
  "Valves",
  "Variable Area Flow Meters",
  "Vibration Monitoring",
  "Videographic Recorders",
  "Voltage Testers",
  "Vortex Flow Meters",
  
  // W categories
  "Water Activity Meters",
  "Water Baths",
  "Water Quality",
  "Weather Monitoring Systems",
  "Wireless Telemetry"
];